name = "CGAL"
uuid = "15fcbb24-5a00-427b-98c5-e32879a22884"
authors = ["Rui Ventura <rventura.pt@outlook.com>"]
version = "0.2.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
libcgal_julia_jll = "e9ad47b2-a301-5fb7-a0bd-6eece649b37c"

[compat]
julia = "1.3"
CxxWrap = "0.11"
Requires = "1"
libcgal_julia_jll = "0.14"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
