name = "CGAL"
uuid = "15fcbb24-5a00-427b-98c5-e32879a22884"
authors = ["Rui Ventura <rventura.pt@outlook.com>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
libcgal_julia_jll = "e9ad47b2-a301-5fb7-a0bd-6eece649b37c"

[compat]
CxxWrap = "= 0.10.1"
julia = "1.3"
libcgal_julia_jll = "0.10.1"
